[package]
name = "raywoke"
description = "Extremely simple raycasting crate"
authors = ["heyimrein", "juni"]
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Ultrasquid9/Raywoke"
maintenance = { status = "actively-developed" }
categories = [ "game-development", "mathematics", ]
keywords = ["gamedev", "raycast", "collision", "2d", "lightweight"]

[dependencies]
dyn-clone = "1"

glam = { version = "0.29", optional = true }
nalgebra = { version = "0.33", optional = true }

[features]
default = []

glam = ["dep:glam"]
nalgebra = ["dep:nalgebra"]
